version: '3.7'

services:
  api:
    container_name: twittertron-server
    build:
      context: ./server
    ports:
      - 5000:5000
    command: npm start
    environment:
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - webnet

  client:
    container_name: twittertron-client
    build:
      context: ./client
    ports:
      - 3000:3000
    command: npm run serve
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
