version: '3.7'

services:
  api:
    container_name: twittetron-server
    build:
      context: ./server
    ports:
      - 5000:5000
    command: npm start
    networks:
      - webnet

  client:
    container_name: twittetron-client
    build:
      context: ./client
    ports:
      - 3000:3000
    command: npm run serve
    networks:
      - webnet

networks:
  webnet:
    driver: bridge